channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - r=3.6
  - black
  - jupyter
  - matplotlib
  - notebook
  - pandas
  - pip
  - ptvsd
  - pylint
  - pytest
  - r-knitr
  - r-languageserver
  - r-markdown
  - snakemake
  - pip:
      - radian
      - snakefmt
