channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - black
  - jupyter
  - matplotlib
  - notebook
  - pandas
  - pip
  - ptvsd
  - pylint
  - pytest
  - snakemake
  - pip:
      - snakefmt
